
/**
 * THIS FILE IS AUTOGENERATED BY `yarn generate`
 *
 * DO NOT EDIT MANUALLY
 */
    
declare module '*GetPosts.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { GetPostsQuery, GetPostsQueryVariables } from 'graphql-gen/types';
  const GetPostsDocument: DocumentNode<
    GetPostsQuery,
    GetPostsQueryVariables
  >;
  export default GetPostsDocument;
}

declare module '*GetPost.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { GetPostQuery, GetPostQueryVariables } from 'graphql-gen/types';
  const GetPostDocument: DocumentNode<
    GetPostQuery,
    GetPostQueryVariables
  >;
  export default GetPostDocument;
}

declare module '*IsAuthenticated.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { IsAuthenticatedQuery, IsAuthenticatedQueryVariables } from 'graphql-gen/types';
  const IsAuthenticatedDocument: DocumentNode<
    IsAuthenticatedQuery,
    IsAuthenticatedQueryVariables
  >;
  export default IsAuthenticatedDocument;
}

declare module '*LoginUser.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { LoginUserMutation, LoginUserMutationVariables } from 'graphql-gen/types';
  const LoginUserDocument: DocumentNode<
    LoginUserMutation,
    LoginUserMutationVariables
  >;
  export default LoginUserDocument;
}

declare module '*UpdatePost.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { UpdatePostMutation, UpdatePostMutationVariables } from 'graphql-gen/types';
  const UpdatePostDocument: DocumentNode<
    UpdatePostMutation,
    UpdatePostMutationVariables
  >;
  export default UpdatePostDocument;
}