
/**
 * THIS FILE IS AUTOGENERATED BY `yarn generate`
 *
 * DO NOT EDIT MANUALLY
 */
    
declare module '*GetArticle.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { GetArticleQuery, GetArticleQueryVariables } from 'graphql-gen/types';
  const GetArticleDocument: DocumentNode<
    GetArticleQuery,
    GetArticleQueryVariables
  >;
  export default GetArticleDocument;
}

declare module '*IsAuthenticated.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { IsAuthenticatedQuery, IsAuthenticatedQueryVariables } from 'graphql-gen/types';
  const IsAuthenticatedDocument: DocumentNode<
    IsAuthenticatedQuery,
    IsAuthenticatedQueryVariables
  >;
  export default IsAuthenticatedDocument;
}

declare module '*LoginUser.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { LoginUserMutation, LoginUserMutationVariables } from 'graphql-gen/types';
  const LoginUserDocument: DocumentNode<
    LoginUserMutation,
    LoginUserMutationVariables
  >;
  export default LoginUserDocument;
}

declare module '*UpdateArticle.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { UpdateArticleMutation, UpdateArticleMutationVariables } from 'graphql-gen/types';
  const UpdateArticleDocument: DocumentNode<
    UpdateArticleMutation,
    UpdateArticleMutationVariables
  >;
  export default UpdateArticleDocument;
}

declare module '*GetArticles.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { GetArticlesQuery, GetArticlesQueryVariables } from 'graphql-gen/types';
  const GetArticlesDocument: DocumentNode<
    GetArticlesQuery,
    GetArticlesQueryVariables
  >;
  export default GetArticlesDocument;
}