# https://hub.docker.com/_/node
FROM node:18

# Create and change to the app directory.
WORKDIR /usr/src/app

COPY package*.json ./
COPY ./yarn.lock ./yarn.lock
COPY ./.env ./.env
COPY ./scripts ./scripts

# Install dependencies.
RUN apt-get -y update
RUN apt-get -y install git
RUN yarn install --only=production

# Copy local code to the container image.
COPY ./build ./build

# Run the web service on container startup.
CMD [ "yarn", "start" ]