name: backend/graphql

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'backend/graphql/**'
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: backend/graphql

jobs:
  # install:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [16.x]

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'yarn'
  #       cache-dependency-path: 'frontend/web/yarn.lock'
  #   - run: yarn ci

  lint:
    # needs: install
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
        fetch-depth: 0
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: 'backend/graphql/yarn.lock'
    - run: yarn ci
    - run: yarn lint:changed