name: frontend/web/lint

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "frontend/web/install"
    types:
      - "completed"

defaults:
  run:
    working-directory: frontend/web

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'frontend/web/yarn'
        cache-dependency-path: 'yarn.lock'
    - run: yarn ci
    - run: yarn lint:changed