name: lint

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**.ts'
      - '.github/workflows/lint.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.prettierrc'
      - 'eslintrc.js'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn ci
    - run: yarn lint:changed